export const Operator =
    {
        'if' : 'If',
        'switch' : 'Switch',
        'struct': 'Struct',
        'union': 'Union',
        'Constant': 'Constant',
        'Identifier': 'Identifier',
        'return': 'Return',
        'while' : 'While',
        'do' : 'Do',
        'for' : 'For',
        '<': 'Less',
        '<=': 'LessEqual',
        '>': 'Greater',
        '>=': 'GreaterEqual',
        '<<': 'LeftShift',
        '>>': 'RightShift',
        '+': 'Plus',
        '++': 'PlusPlus',
        '-': 'Minus',
        '--': 'MinusMinus',
        '*': 'Star',
        '/': 'Div',
        '%': 'Mod',
        '&': 'And',
        '|': 'Or',
        '&&': 'AndAnd',
        '||': 'OrOr',
        '^': 'Caret',
        '!': 'Not',
        '~': 'Tilde',
        '?': 'Question',
        ':': 'colon',
        ',': 'Comma',
        '=': 'Assign',
// '*=' | '/=' | '%=' | '+=' | '-=' | '<<=' | '>>=' | '&=' | '^=' | '|='
    '*=': 'StarAssign',
    '/=': 'DivAssign',
    '%=': 'ModAssign',
    '+=': 'PlusAssign',
    '-=': 'MinusAssign',
    '<<=': 'LeftShiftAssign',
    '>>=': 'RightShiftAssign',
    '&=': 'AndAssign',
    '^=': 'XorAssign',
    '|=': 'OrAssign',
    '==': 'Equal',
    '!=': 'NotEqual',
    '->': 'Arrow',
    '.': 'Dot',
    '...': 'Ellipsis'
};